spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus?useUnicode=true&characterEncoding=UTF-8
    username: test
    password: GDleroy_123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

logging:
  level:
    root: info
    com.shnu.campus: debug
server:
  port: 8081

comment.avatar: /img/avatar.png

